// <auto-generated />
using System;
using GymLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymLog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230726012321_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GymLog.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GymLog.Models.BodyPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BodyParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Back"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Legs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Core"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Arms"
                        });
                });

            modelBuilder.Entity("GymLog.Models.BodyPartExercise", b =>
                {
                    b.Property<int>("BodyPartId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.HasKey("BodyPartId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("BodyPartExercises");

                    b.HasData(
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 1
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 1
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 2
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 2
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 3
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 3
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 4
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 4
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 4
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 5
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 5
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 5
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 6
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 6
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 6
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 7
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 7
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 7
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 8
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 8
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 8
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 9
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 9
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 9
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 10
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 10
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 10
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 11
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 12
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 13
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 14
                        },
                        new
                        {
                            BodyPartId = 3,
                            ExerciseId = 14
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 15
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 15
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 16
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 16
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 16
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 17
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 17
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 17
                        },
                        new
                        {
                            BodyPartId = 3,
                            ExerciseId = 18
                        },
                        new
                        {
                            BodyPartId = 3,
                            ExerciseId = 19
                        },
                        new
                        {
                            BodyPartId = 3,
                            ExerciseId = 20
                        },
                        new
                        {
                            BodyPartId = 3,
                            ExerciseId = 21
                        },
                        new
                        {
                            BodyPartId = 3,
                            ExerciseId = 22
                        },
                        new
                        {
                            BodyPartId = 3,
                            ExerciseId = 23
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 23
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 24
                        },
                        new
                        {
                            BodyPartId = 3,
                            ExerciseId = 24
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 24
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 25
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 26
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 27
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 28
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 29
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 30
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 31
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 32
                        },
                        new
                        {
                            BodyPartId = 1,
                            ExerciseId = 33
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 33
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 33
                        },
                        new
                        {
                            BodyPartId = 5,
                            ExerciseId = 34
                        },
                        new
                        {
                            BodyPartId = 5,
                            ExerciseId = 35
                        },
                        new
                        {
                            BodyPartId = 5,
                            ExerciseId = 36
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 37
                        },
                        new
                        {
                            BodyPartId = 5,
                            ExerciseId = 37
                        },
                        new
                        {
                            BodyPartId = 4,
                            ExerciseId = 38
                        },
                        new
                        {
                            BodyPartId = 5,
                            ExerciseId = 38
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 39
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 40
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 41
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 42
                        },
                        new
                        {
                            BodyPartId = 2,
                            ExerciseId = 43
                        },
                        new
                        {
                            BodyPartId = 6,
                            ExerciseId = 43
                        });
                });

            modelBuilder.Entity("GymLog.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = 3,
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Push Ups"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wide Push Ups"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Diamond Push Ups"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Archer Push Ups"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Decline PushUps"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ring Dips"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Straight Bar Dips"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dumbell Pullover"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Single Arm Row"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bent Over Row"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Single Leg Deadlift"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Pulldowns Behind Head"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Pull Row"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Pull Ups"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Calf Raises"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Lunges"
                        },
                        new
                        {
                            Id = 21,
                            Name = "One Leg Claf Raises"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Pistol Squat"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Box Jumps"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bridge"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Hanging Knee Raises"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Leg Raises"
                        },
                        new
                        {
                            Id = 29,
                            Name = "L-Sit Pull Ups"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Russian Twist"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Sit Ups"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Toes To Bar"
                        },
                        new
                        {
                            Id = 33,
                            Name = "V-Ups"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Knee Elbow Push Ups"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Front Raises"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Lateral Raises"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Upright Row"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Bent Over Reverse Fly"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Military Press - OHP"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Bicep Curl"
                        },
                        new
                        {
                            Id = 41,
                            Name = "French Press"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Hummer Curls"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Preacher Bicep Curl"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Chin Ups"
                        });
                });

            modelBuilder.Entity("GymLog.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.Property<int>("WorkoutSegmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSegmentId");

                    b.ToTable("Sets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 2
                        },
                        new
                        {
                            Id = 4,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 2
                        },
                        new
                        {
                            Id = 5,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 3
                        },
                        new
                        {
                            Id = 6,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 3
                        },
                        new
                        {
                            Id = 7,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 4
                        },
                        new
                        {
                            Id = 8,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 4
                        },
                        new
                        {
                            Id = 9,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 5
                        },
                        new
                        {
                            Id = 10,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 5
                        },
                        new
                        {
                            Id = 11,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 6
                        },
                        new
                        {
                            Id = 12,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 6
                        },
                        new
                        {
                            Id = 13,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 7
                        },
                        new
                        {
                            Id = 14,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 7
                        },
                        new
                        {
                            Id = 15,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 8
                        },
                        new
                        {
                            Id = 16,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 8
                        },
                        new
                        {
                            Id = 17,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 9
                        },
                        new
                        {
                            Id = 18,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 9
                        },
                        new
                        {
                            Id = 19,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 10
                        },
                        new
                        {
                            Id = 20,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 10
                        },
                        new
                        {
                            Id = 21,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 11
                        },
                        new
                        {
                            Id = 22,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 11
                        },
                        new
                        {
                            Id = 23,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 12
                        },
                        new
                        {
                            Id = 24,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 12
                        },
                        new
                        {
                            Id = 25,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 13
                        },
                        new
                        {
                            Id = 26,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 13
                        },
                        new
                        {
                            Id = 27,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 14
                        },
                        new
                        {
                            Id = 28,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 14
                        },
                        new
                        {
                            Id = 29,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 15
                        },
                        new
                        {
                            Id = 30,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 15
                        },
                        new
                        {
                            Id = 31,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 16
                        },
                        new
                        {
                            Id = 32,
                            Reps = 12,
                            Weight = 0f,
                            WorkoutSegmentId = 16
                        },
                        new
                        {
                            Id = 33,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 17
                        },
                        new
                        {
                            Id = 34,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 17
                        },
                        new
                        {
                            Id = 35,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 18
                        },
                        new
                        {
                            Id = 36,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 18
                        },
                        new
                        {
                            Id = 37,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 19
                        },
                        new
                        {
                            Id = 38,
                            Reps = 4,
                            Weight = 0f,
                            WorkoutSegmentId = 19
                        },
                        new
                        {
                            Id = 39,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 20
                        },
                        new
                        {
                            Id = 40,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 20
                        },
                        new
                        {
                            Id = 41,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 21
                        },
                        new
                        {
                            Id = 42,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 21
                        },
                        new
                        {
                            Id = 43,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 22
                        },
                        new
                        {
                            Id = 44,
                            Reps = 8,
                            Weight = 0f,
                            WorkoutSegmentId = 22
                        });
                });

            modelBuilder.Entity("GymLog.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sample Workout 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sample Workout 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sample Workout 3"
                        });
                });

            modelBuilder.Entity("GymLog.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sample Workout 1",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sample Workout 2",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TemplateId = 2
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sample Workout 3",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TemplateId = 3
                        });
                });

            modelBuilder.Entity("GymLog.Models.WorkoutSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("WeightType")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutSegments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "2 x 1-4",
                            ExerciseId = 1,
                            TemplateId = 1,
                            WeightType = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "2 x 1-4",
                            ExerciseId = 2,
                            TemplateId = 1,
                            WeightType = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "2 x 1-4",
                            ExerciseId = 3,
                            TemplateId = 1,
                            WeightType = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "2 x 1-4",
                            ExerciseId = 10,
                            TemplateId = 1,
                            WeightType = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "2 x 1-4",
                            ExerciseId = 11,
                            TemplateId = 1,
                            WeightType = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "2 x 1-4",
                            ExerciseId = 12,
                            TemplateId = 1,
                            WeightType = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "2 x 1-4",
                            ExerciseId = 33,
                            TemplateId = 1,
                            WeightType = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "2 x 10-12",
                            ExerciseId = 4,
                            TemplateId = 2,
                            WeightType = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "2 x 10-12",
                            ExerciseId = 6,
                            TemplateId = 2,
                            WeightType = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "2 x 10-12",
                            ExerciseId = 7,
                            TemplateId = 2,
                            WeightType = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "2 x 10-12",
                            ExerciseId = 14,
                            TemplateId = 2,
                            WeightType = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "2 x 10-12",
                            ExerciseId = 15,
                            TemplateId = 2,
                            WeightType = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "2 x 10-12",
                            ExerciseId = 24,
                            TemplateId = 2,
                            WeightType = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "2 x 10-12",
                            ExerciseId = 33,
                            TemplateId = 2,
                            WeightType = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "2 x 10-12",
                            ExerciseId = 34,
                            TemplateId = 2,
                            WeightType = 0
                        },
                        new
                        {
                            Id = 16,
                            Description = "2 x 10-12",
                            ExerciseId = 40,
                            TemplateId = 2,
                            WeightType = 0
                        },
                        new
                        {
                            Id = 17,
                            Description = "2 x 6-8",
                            ExerciseId = 1,
                            TemplateId = 3,
                            WeightType = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "2 x 6-8",
                            ExerciseId = 10,
                            TemplateId = 3,
                            WeightType = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "2 x 6-8",
                            ExerciseId = 20,
                            TemplateId = 3,
                            WeightType = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "2 x 6-8",
                            ExerciseId = 30,
                            TemplateId = 3,
                            WeightType = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "2 x 6-8",
                            ExerciseId = 40,
                            TemplateId = 3,
                            WeightType = 1
                        },
                        new
                        {
                            Id = 22,
                            Description = "2 x 6-8",
                            ExerciseId = 41,
                            TemplateId = 3,
                            WeightType = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymLog.Models.BodyPartExercise", b =>
                {
                    b.HasOne("GymLog.Models.BodyPart", "BodyPart")
                        .WithMany("BodyPartExercises")
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymLog.Models.Exercise", "Exercise")
                        .WithMany("BodyPartExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyPart");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GymLog.Models.Set", b =>
                {
                    b.HasOne("GymLog.Models.WorkoutSegment", "WorkoutSegment")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSegment");
                });

            modelBuilder.Entity("GymLog.Models.Template", b =>
                {
                    b.HasOne("GymLog.Models.AppUser", "AppUser")
                        .WithMany("Templates")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("GymLog.Models.Workout", b =>
                {
                    b.HasOne("GymLog.Models.AppUser", "AppUser")
                        .WithMany("Workouts")
                        .HasForeignKey("AppUserId");

                    b.HasOne("GymLog.Models.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("GymLog.Models.WorkoutSegment", b =>
                {
                    b.HasOne("GymLog.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymLog.Models.Template", "Template")
                        .WithMany("WorkoutSegments")
                        .HasForeignKey("TemplateId");

                    b.HasOne("GymLog.Models.Workout", "Workout")
                        .WithMany("WorkoutSegments")
                        .HasForeignKey("WorkoutId");

                    b.Navigation("Exercise");

                    b.Navigation("Template");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GymLog.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GymLog.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymLog.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GymLog.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymLog.Models.AppUser", b =>
                {
                    b.Navigation("Templates");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("GymLog.Models.BodyPart", b =>
                {
                    b.Navigation("BodyPartExercises");
                });

            modelBuilder.Entity("GymLog.Models.Exercise", b =>
                {
                    b.Navigation("BodyPartExercises");
                });

            modelBuilder.Entity("GymLog.Models.Template", b =>
                {
                    b.Navigation("WorkoutSegments");
                });

            modelBuilder.Entity("GymLog.Models.Workout", b =>
                {
                    b.Navigation("WorkoutSegments");
                });

            modelBuilder.Entity("GymLog.Models.WorkoutSegment", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
